[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["MultisigWallet"]
# Helps with better test coverage
fuzz_runs = 1000

[profile.ci]
fuzz_runs = 10_000
verbosity = 4

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true